unique_ids:
  assets:
    standard-page.html: RGKOLT7BJBXKUIS4L3UTEZEU5VK3NNUU
    theme.css: JTXICB4ZC2A6X543UFLC3JU4S46LTEYL
  forms:
    Form1: VMPMMP42MVFIFGOBJNJ5URKHJHC66LYJ
  modules: {}
  scripts: {}
  server_modules: {}
